### ISSUE TITLE
App Does Not Have A ReadMe File

### ISSUE THREAD

**Issue by tochiOz** [Next-Inn/Jointtaskfoundation-Fe#1]
Please @lovisgod, it will make sense if there are readme files for each of the projects, So i will assume @odomfavour has done some good about app, but i have no idea why and what the app does or even how to make use of the app.

Please @odomfavour , @Orung , please take note.

**Comment by odomfavour** [comment]
I have added the readme file.

**Comment by lovisgod** [comment]
cool. Thanks @odomfavour
